# Generated by Django 5.1.3 on 2025-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondPagamento',
            fields=[
                ('id_cond_pagamento', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_do_cartao', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=45)),
                ('id_plano', models.IntegerField()),
                ('data_validade', models.CharField(max_length=45)),
                ('cvv', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cond_pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrosPossiveis',
            fields=[
                ('id_erro', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'erros_possiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id_exercicios', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_exercicio', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=1000)),
                ('musculos_envolvidos', models.CharField(max_length=50)),
                ('id_nivel_dificuldade', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'exercicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelDificuldade',
            fields=[
                ('idnivel_dificuldade', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_nivel_dificuldade', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'nivel_dificuldade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('adm', models.IntegerField(blank=True, null=True)),
                ('ativado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idpessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('senha', models.CharField(blank=True, max_length=45, null=True)),
                ('id_plano', models.IntegerField(blank=True, null=True)),
                ('id_perfil', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False)),
                ('nome_plano', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'plano',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('nome_treino', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'treino',
                'managed': False,
            },
        ),
    ]
