# Generated by Django 5.1.3 on 2025-04-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicios',
            options={'managed': True},
        ),
    ]
