# Generated by Django 5.1.3 on 2025-04-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0002_alter_exercicios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicios',
            name='imagem',
            field=models.ImageField(default='tb.png', null=True, upload_to='exercicios/'),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='id_nivel_dificuldade',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='exercicios',
            unique_together={('id_exercicios', 'id_nivel_dificuldade')},
        ),
    ]
