# Generated by Django 5.1.3 on 2025-04-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0003_exercicios_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='id_nivel_dificuldade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb_app.niveldificuldade'),
        ),
    ]
