# Generated by Django 5.1.6 on 2025-04-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0005_relexerciciosmusculos_relplanotreino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musculosenvolvidos',
            options={'managed': False},
        ),
    ]
